version: 2

python:
  install:
    - path: .
      extra_requirements:
        - docs
build:
  os: ubuntu-lts-latest
  tools:
    python: latest
  jobs:
    post_checkout:
      - git fetch --unshallow || true
sphinx:
  configuration: docs/conf.py
