name: 👀 coverage

on:
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        description: Codecov token of the main repository
        required: false


permissions:
  contents: read

jobs:
  ctest:
    name: ${{ matrix.coverage }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        coverage: [ unit_tests, c_api, fortran_api ]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: lukka/get-cmake@latest
      - name: Get test coverage for ${{ matrix.coverage }}
        uses: lukka/run-cmake@v10
        with:
          workflowPreset: "ci-coverage-${{ matrix.coverage }}"
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          name: ${{ matrix.coverage }} coverage
          flags: ${{ matrix.coverage }}
          verbose: true

  pytest:
    name: python_api
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Setup spglib
        run: |
          python -m pip install --upgrade pip
          pip install -e .[test-cov] \
             --config-settings=cmake.define.CMAKE_C_COMPILER=gcc \
             --config-settings=cmake.define.SPGLIB_WITH_TESTS=ON \
             --config-settings=cmake.define.SPGLIB_TEST_COVERAGE=ON \
             --config-settings=build-dir=build
      - name: Test pytest with coverage
        run: pytest --cov=spglib
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          name: python_api coverage
          flags: python_api
          verbose: true
